// <auto-generated />
namespace CentralAtivos.Repository.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class StatusItem : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(StatusItem));
        
        string IMigrationMetadata.Id
        {
            get { return "201909272146498_StatusItem"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
